### ISSUE TITLE
Dynamic target and limits (feature request)

### ISSUE THREAD

**Issue by dorinpirvu** [KensoBI/spc-chart#34] opened 2024-02-13 08:52 UTC
Hello, 
I think it could be useful to be able to be able to select the target and limits from fields/columns returned by the query (dynamic values).
Use case: different products in a database, each with its own target and limits.
Thanks!

**Comment by mrtomeq** [comment] 2024-02-15 14:34
Hi @dorinpirvu, I believe we already have this functionality. You can add custom values to the chart by using the `table` query in combination with your `timeseries` query.

Check out this example: [SPC Custom Fields Demo](https://demo.kensobi.com/d/e64af8b8-1546-4b89-a1b3-650d06c8e38f/spc-custom-fields?orgId=1).

You need to add two queries - `table` and `timeseries`.

**Time series**
```SQL
SELECT 
   value, time 
FROM 
  measurement
WHERE characteristic_id = 5697
```

**Table**
```SQL
SELECT nominal, lsl, usl, 260.5 as anyCustomValue FROM characteristic WHERE id = 5697
```

Next, in the panel editor, select the constants dropdown. Extra columns from table should be available to select. 

![image](https://github.com/KensoBI/spc-panel/assets/8570009/d21a1aa9-bdd7-40e4-a98d-0b1c2fae17b7)

Check out [Custom constants values in the chart documentation](https://docs.kensobi.com/panels/spc) section for details.

We will be submitting this release to Grafana for review, although it may take a few days for them to push it to the Grafana plugin repository. In the meantime, you can download the latest version from https://cdn.kensobi.com/plugins/prod/kensobi-spc-panel.zip or https://github.com/KensoBI/spc-panel/releases

Let me know if this is what you've been looking for or if you have any questions.

**Comment by dorinpirvu** [comment] 2024-02-16 10:41
Hello @mrtomeq, thanks for the info, indeed the option appears with this version of the plugin. 
It does not work with the version available on Grafana.
On the other hand, I see some limitations:
- what if limits vary during the time displayed?
- what if the measured value needs weighting by another component? (for example fat content of a product: average value should take into consideration batch quantity)
I attach a screen shot with different visualisations, one is the SPC panel, another is the display of same data using timeseries panel and the other is similar to the other feature request I opened. 
Of course, these are nice to have, otherwise kudos for the panel plugin!
![image](https://github.com/KensoBI/spc-panel/assets/127939087/0f46af37-eed0-4bbd-8aca-8c4b3782440e)

**Comment by mrtomeq** [comment] 2024-02-16 18:05
> what if limits (and/or target) vary during the time displayed?

I believe we currently take only the last value and use it as a constant. Constants remain fixed and do not fluctuate. This panel currently does not support multiple time series on one chart. Variable limits would essentially be a time series. We discussed this some time ago and decided not to implement it until our users ask for it.  Now, that you asked we will have this conversation again 😀. I will create another issue where we all can shape the requirements. 

> what if the measured value needs weighting by another component? (for example fat content of a product: average value should take into consideration batch quantity)

Correct me if I'm wrong, but I believe you are referring to `sample size`. With `sample size`, we assume a **fixed** number of measurements for a given sample size, i.e., 

![image](https://github.com/KensoBI/spc-panel/assets/8570009/2461212e-430f-492c-8e12-c0199f1182d5)

A sample size of 5 with the aggregation type `mean` means we group all measurements into 5-measurement buckets and then take the average of these 5 values in a bucket. When you add the `mean` constant, it will calculate the mean of means.

![image](https://github.com/KensoBI/spc-panel/assets/8570009/110be4d0-e686-40bb-8951-42f978237237)

>if I add Mean (or any other constant after the first three) and try to change the color, it doesn't work (color works for first three constants added) 

I was unable to reproduce it in the latest version. Could you please confirm if this is still an issue in the latest version (not from the Grafana plugin repo)?

BTW, Are you using any of the calculations like X-bar or S-bar?

**Comment by mrtomeq** [comment] 2024-02-16 20:35
@dorinpirvu off topic but how you were able to set a string of x-axis in XY chart? I tried overwrites but I was unable to get it to work. 

![image](https://github.com/KensoBI/spc-panel/assets/8570009/c8c33b06-6a6a-42c2-a3cf-c2cf56e87ea3)

**Comment by dorinpirvu** [comment] 2024-02-19 09:38
Hello @mrtomeq and thanks for the comments, I'll try to tackle each one:
- timeseries for constants: yeey, I hope I generated constructive discussions :)
- averaging: I was talking about weighted average instead of average, here's an example:
  A production batch that has 10t and 5% fat (=500 fat units) and another batch that has 20t and 3% fat (=600 fat units) (same product type, target of 4% fat)
 We are checking the fat percentage in SPC, and if i take these two samples and calculate the mean of the measured fat percentage values, it will be 4% ((5%+3%) / 2). We are actually using the weighted average (10t*5% + 20t*3%) / (10t+20t) which gives 3.66%. 
Personally I am quite new to this, so I'm not aware of the implications behind, but this is what we're looking for. I hope this clarifies a bit this point.

- colors: yes, now I am using your version of the plugin, I will try to replicate again, because it seems to happen only in a specific situation and I'll try to tell you the exact steps
- no, for now we are not using X-bar or S-Bar calculations, but might happen in the future
- the strings on the x-axis of XY Chart panel is just a simple value mapping which works good enough if the panel is not too wide - see pic; for wide panels i get numeric values between the strings
![image](https://github.com/KensoBI/spc-panel/assets/127939087/6bd87b51-5207-416f-b26d-c4f0696cfe1f)

**Comment by dorinpirvu** [comment] 2024-02-19 11:41
Colors issue:
- when there is no separate table for limits; any constant i add to the chart: can not change color until i add the fifth constant (fifth constant changes the color of the first one, the sixth constant changes the color of the second constant, etc)
- when there is a separate table for limits (for example usl1, lsl1, nominal1): adding these constants to the graph is ok, each color can be changed. Adding other constants to the chart: each new constant changes the color of the previous constant, except for the first one that can not change color - it does not affect constants coming from table query;
- this behavior does not change if there are Nominal, USL, LSL values manually input, or if a sample size different from 1 is selected; the order of adding a constant does not seem to matter;
- attached pic: 
![image](https://github.com/KensoBI/spc-panel/assets/127939087/39ebb6ed-9aea-41d2-a662-31d7e4143355)
colors for usl1, lsl1, nominal1 can be changed; LSL color can not be changed, USL color (color-picker) changes the color for LSL, etc...
This is the plugin version you provided, not the one from Grafana repository, unfortunately I can not test right now if the issue also appears in that version

**Comment by mrGnowak** [comment] 2024-02-21 17:26
#40 Color and line width fix

**Comment by mrtomeq** [comment] 2024-11-22 22:14
We added support for multiple series in version 2 (not jet published to Grafana plugin repository). SPC charts are calculated for all series by default. However, you can disable aggregation and provide variable limits as series through an SQL query. You can still add constants from hardcoded values or limits from a lookup query.

As for calculated variable limits, these will be introduced with new chart types, including:

- p-chart
- np-chart
- c-chart
- u-chart

**Closed by mrtomeq** 2024-11-22 22:14 UTC
